name:                stackpak
version:             1.0.3
github:              "githubuser/stackpak"
license:             GPLv2
author:              "Richard Szibele"
maintainer:          "richard@szibele.com"
copyright:           "2018 Richard Szibele"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Gitlab at <https://gitlab.com/rszibele/stackpak#readme>

dependencies:
- base >= 4.7 && < 5
- cmdargs
- text
- directory
- yaml
- aeson
- aeson-pretty
- process
- string-conversions
- containers
- unordered-containers
- parsec
- extra
- hashable
- MissingH
- split
- transformers
- cryptonite
- bytestring
- http-client
- http-client-tls
- http-conduit
- http-types

library:
  source-dirs: src

executables:
  stackpak:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stackpak

tests:
  stackpak-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stackpak
